### PR TITLE
Migrate maven plugin to maven-publish and fix some deprecation warnings.

### PR DESCRIPTION
**Pull request by jameshilliard**

### CODE REVIEW

**Comment by jameshilliard** [comment]
Rebased

**Comment by ar** [comment]
> Rebased

Thank you for the rebase. I'm afraid we'll hold this PR until next release, so I may have to ask you for yet another rebase.

**Comment by alcarraz** [comment]
Hi @jameshilliard tried to test this by publishing to local maven and the build failed for `qi-core` module :disappointed: 

```
$ ./gradlew publishToMavenLocal
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :modules:qi-core
Using Gradle Vaadin Plugin 2.0.0.beta2

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':modules:qi-eeuser:publishMavenJavaPublicationToMavenLocal'.
> Publishing is not able to resolve a dependency on a project with multiple publications that have different coordinates.
  Found the following publications in project ':modules:qi-core':
    - Maven publication 'mavenJava' with coordinates org.jpos.ee:jpos.ee:2.2.7-SNAPSHOT
    - Maven publication 'mavenQICore' with coordinates org.jpos.ee:jposee-qi-core:2.2.7-SNAPSHOT

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 55s
```

**Comment by jameshilliard** [comment]
@alcarraz Just pushed a fix for that error.

**Comment by ar** [comment]
In 35b025481e we've upgraded to `maven-publish` plugin, and up to Gradle 6.8.2. We have some issues with Vaadin's Gradle plugin that does not support Gradle 7 yet., so we are capping at 6.8.2 for a (hopefully little) while.

**Pull request closed without merging**
