### PR TITLE
Gives HttpQuery subclasses ability to customize HTTP client

### PR DESCRIPTION
**Pull request by bmomcilov**

### CODE REVIEW

**Comment by barspi** [comment]
I'm not sure how you want to subclass `HttpQuery`

**Comment by barspi** [comment]
I'm not sure how you want to subclass `HttpQuery`
Maybe you want to subclass the client building process, but `buildClient()` already calls `build()` (does it finalize the building?)
I think a better idea would be to have a `getClientBuilder()`  that returns a **not-yet-built()** client, so you can override **that** method, call `super()`, and then add your own build options.

**Comment by bmomcilov** [comment]
> I'm not sure how you want to subclass `HttpQuery`
> Maybe you want to subclass the client building process, but `buildClient()` already calls `build()` (does it finalize the building?)
> I think a better idea would be to have a `getClientBuilder()` that returns a **not-yet-built()** client, so you can override **that** method, call `super()`, and then add your own build options.

This way you can extend `HttpQuery` class, override `buildClient(...)` and completely build HTTP instance yourself which would be helpful for testing purposes (to actually return mock instance). As long as it confirms CloseableHttpAsyncClient abstract it is ok.

**Comment by barspi** [comment]
ahh, mocking is your business ;-)
In any case, maybe *your* needs, and what I explained above can co-exist if it's not too much trouble

**Comment by bmomcilov** [comment]
Not at all, let me add that.

**Review by ar — APPROVED** [review]

**Pull request merged**
